apiVersion: v1
data:
  spring.application.name: USER-SERVICE
  spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
  spring.datasource.url: jdbc:mysql://istory-db-lb:3306/istory
  spring.jpa.database-platform: org.hibernate.dialect.MySQLDialect
  spring.jpa.hibernate.ddl-auto: update
  spring.jpa.show-sql: "true"
kind: ConfigMap
metadata:
  name: istory-app-config
---
apiVersion: v1
kind: Service
metadata:
  name: istory-app-lb
spec:
  ports:
  - name: istory-app-lb
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: istory-app
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 800
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: istory-app
  name: istory-app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: istory-app
  template:
    metadata:
      labels:
        app: istory-app
    spec:
      containers:
      - env:
        - name: spring.datasource.password
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWORD
              name: istory-db-secret
        - name: spring.datasource.username
          valueFrom:
            secretKeyRef:
              key: MYSQL_USER
              name: istory-db-secret
        envFrom:
        - configMapRef:
            name: istory-app-config
        image: jjsungpp/istory:latest
        name: istory
        ports:
        - containerPort: 3306
          name: istory
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
          successThreshold: 2
          timeoutSeconds: 3
      initContainers:
      - command:
        - sh
        - -c
        - until mysqladmin ping -u ${MYSQL_USER} -p${MYSQL_PASSWORD} -h istory-db-lb;
          do echo waiting for database; sleep 2; done;
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: MYSQL_USER
              name: istory-db-secret
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWORD
              name: istory-db-secret
        image: mysql:8.0
        name: check-mysql-ready
      restartPolicy: Always
      volumes:
      - configMap:
          name: istory-app-config
        name: application-config
